name: CI
on: [push, pull_request]
jobs:
  macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -project EstEIDTokenApp.xcodeproj -target package CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO DSTROOT=$PWD/tmp CURRENT_PROJECT_VERSION=${{ github.run_number }} install
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pkg
        path: ./*.pkg
